allow_shell: false
allow_file_write_outside_workspace: false
allow_os_automation: false
allow_network: false
require_confirmation_for:
  - cloud_deploy
  - file_delete
  - install_software
  - login
  - payment
max_daily_budget_usd: 0
